// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FolderExplorer.Models;
using Microsoft.EntityFrameworkCore;

namespace FolderExplorer.Data;

public partial class FoldersContext : DbContext
{
    public FoldersContext()
    {
    }

    public FoldersContext(DbContextOptions<FoldersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Folder> Folder { get; set; }

    public virtual DbSet<FolderRelations> FolderRelations { get; set; }

 
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Folder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Folder__3213E83F944D8C13");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<FolderRelations>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FolderRe__3213E83F85133195");

            entity.HasOne(d => d.Child).WithMany(p => p.FolderRelationsChild)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FolderRel__child__52593CB8");

            entity.HasOne(d => d.Father).WithMany(p => p.FolderRelationsFather)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FolderRel__fathe__5165187F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}