// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FolderExplorer.Models;
using Microsoft.EntityFrameworkCore;

namespace FolderExplorer.Data;

public partial class FoldersContext : DbContext
{
    public FoldersContext()
    {
    }

    public FoldersContext(DbContextOptions<FoldersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Folder> Folder { get; set; }

    public virtual DbSet<FolderRelations> FolderRelations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Folder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Folder__3213E83F15BC6B06");
        });

        modelBuilder.Entity<FolderRelations>(entity =>
        {
            entity.HasOne(d => d.Child).WithMany().HasConstraintName("FK__FolderRel__child__398D8EEE");

            entity.HasOne(d => d.Father).WithMany().HasConstraintName("FK__FolderRel__fathe__38996AB5");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}