// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FolderExplorer.Models;

[Keyless]
public partial class FolderRelations
{
    [Column("father_id")]
    public int? FatherId { get; set; }

    [Column("child_id")]
    public int? ChildId { get; set; }

    [ForeignKey("ChildId")]
    public virtual Folder Child { get; set; }

    [ForeignKey("FatherId")]
    public virtual Folder Father { get; set; }
}